### PR TITLE
impediments limit

### PR DESCRIPTION
**Pull request by g4s8**
zerocracy/farm#447 - added login for impediment, it's required to count impediments for a user.
Also migration added: all previous impediments are treated as requested by `0crat`

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#281](https://github.com/zerocracy/datum/issues/281) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#281](https://github.com/zerocracy/datum/issues/281) is assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/472027532). The budget is 15 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§27](http://datum.zerocracy.com/pages/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](https://www.0crat.com/u/yegor256) (the architect) right in this ticket. If you decide that this PR should not be accepted ever, also inform the architect.

**Comment by carlosmiranda** [comment]
@yegor256 looks good to merge

**Comment by yegor256** [comment]
@g4s8 looks like a duplication of data to me. We already know who is the owner of the order. And one order may have one impediment. So, it's always obvious how many impediments a user has - we just combine `impediments.xml` and `orders.xml`. Or I'm wrong?

**Comment by g4s8** [comment]
@yegor256 but what if a user requests an impediment and ARC assigned someone else to this job, or user just resigned? Maybe we have to remove this impediment in such case?

**Comment by yegor256** [comment]
@g4s8 I think we do that. Once the order is removed, the impediment automatically goes away: https://github.com/zerocracy/datum/blob/master/auto/pm/in/orders/01-impediments-remove.xsl

**Comment by g4s8** [comment]
@yegor256 OK, so I'm clinsing this one

**Comment by 0crat** [comment]
Order was finished, quality was "acceptable": +15 points just awarded to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), total is [+1500](https://www.0crat.com/u/carlosmiranda)

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://datum.zerocracy.com/pages/policy.html#28): +15 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+10489](https://www.0crat.com/u/yegor256)

**Pull request closed without merging**
