### PR TITLE
Small grammar improvements

### PR DESCRIPTION
**Pull request by filfreire**
/cc @g4s8

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#271](https://github.com/zerocracy/datum/issues/271) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#271](https://github.com/zerocracy/datum/issues/271) is assigned to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx). The budget is 15 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§27](http://datum.zerocracy.com/pages/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](https://www.0crat.com/u/yegor256) (the architect) right in this ticket. If you decide that this PR should not be accepted ever, also inform the architect.

**Comment by 0crat** [comment]
@fabriciofx[/z](https://www.0crat.com/u/fabriciofx) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://datum.zerocracy.com/pages/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
@fabriciofx[/z](https://www.0crat.com/u/fabriciofx) this job was assigned to you 8 days ago. It will be taken away from you soon, unless you close it, see [§8](http://datum.zerocracy.com/pages/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @fabriciofx[/z](https://www.0crat.com/u/fabriciofx) resigned from [#271](https://github.com/zerocracy/datum/issues/271), please stop working

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://datum.zerocracy.com/pages/policy.html#8): -15 points just awarded to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx), total is [+390](https://www.0crat.com/u/fabriciofx)

**Comment by 0crat** [comment]
This pull request [#271](https://github.com/zerocracy/datum/issues/271) is assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/472210949). The budget is 15 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§27](http://datum.zerocracy.com/pages/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](https://www.0crat.com/u/yegor256) (the architect) right in this ticket. If you decide that this PR should not be accepted ever, also inform the architect.

**Comment by carlosmiranda** [comment]
@yegor256 looks good to merge here

**Comment by yegor256** [comment]
@0crat refuse

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zerocracy/datum/issues/271#issuecomment-366785065))

@yegor256 The user @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) resigned from [#271](https://github.com/zerocracy/datum/issues/271), please stop working

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zerocracy/datum/issues/271#issuecomment-366785065))

@yegor256 Job `gh:zerocracy/datum#271` is not assigned, can't get performer

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zerocracy/datum/issues/271#issuecomment-366785065))

@yegor256 Job `gh:zerocracy/datum#271` is not assigned, can't get performer

**Comment by 0crat** [comment]
This pull request [#271](https://github.com/zerocracy/datum/issues/271) is assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/501937819). The budget is 15 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§27](http://datum.zerocracy.com/pages/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](https://www.0crat.com/u/yegor256) (the architect) right in this ticket. If you decide that this PR should not be accepted ever, also inform the architect.

**Comment by 0crat** [comment]
Order was finished, quality was "acceptable": +15 points just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8), total is [+4255](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://datum.zerocracy.com/pages/policy.html#28): +15 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+10154](https://www.0crat.com/u/yegor256)

**Pull request merged**
