### PR TITLE
zerocracy/farm#165 - archive schema

### PR DESCRIPTION
**Pull request by g4s8**
zerocracy/farm#165 - archive schema, according to https://github.com/zerocracy/farm/issues/165#issuecomment-320449149

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this pull request

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#63` is in scope.

**Comment by 0crat** [comment]
+15 points just awarded to @g4s8, total is [+750](http://www.0crat.com/u/g4s8).

**Comment by yegor256** [comment]
@rultor merge

**Comment by g4s8** [comment]
@yegor256 make a release please with this changes

**Comment by yegor256** [comment]
@rultor release, tag is `0.33`

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#63` assigned to @carlosmiranda, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
@carlosmiranda resigned from `gh:zerocracy/datum#63`, please stop working.

**Pull request merged**
