### PR TITLE
Ruby update

### PR DESCRIPTION
**Pull request by g4s8**
#396 - updated ruby to 2.6.0

### CODE REVIEW

**Comment by g4s8** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job [#397](https://github.com/zerocracy/datum/issues/397) is now in scope, role is `REV`

**Comment by g4s8** [comment]
@rultor merge

**Comment by g4s8** [comment]
@yegor256 can you please merge this PR? It's needed to change `.rultor.yml` config to build with new ruby version (see https://github.com/zerocracy/datum/pull/397/commits/3d0dd4505f0ac4bc38a39f1bd08c7391557361e0), but it's not possible to do from PR, because rulor takes config file from master branch.

**Comment by g4s8** [comment]
@yegor256 ping, can you please look at this PR? (see https://github.com/zerocracy/datum/pull/397#issuecomment-468780069)

**Comment by g4s8** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#397` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#397](https://github.com/zerocracy/datum/issues/397) is now out of scope

**Pull request merged**
