### PR TITLE
zerocracy/farm#166 milestones.xml and precedences.xml

### PR DESCRIPTION
**Pull request by carlosmiranda**
zerocracy/farm#166 Added `milestones.xml` and `precedences.xml`

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this pull request

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#65` is in scope.

**Comment by 0crat** [comment]
+15 points just awarded to @carlosmiranda, total is [+345](http://www.0crat.com/u/carlosmiranda).

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#65` assigned to @carlosmiranda, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
@carlosmiranda resigned from `gh:zerocracy/datum#65`, please stop working.

**Pull request merged**
