### PR TITLE
Project title

### PR DESCRIPTION
**Pull request by g4s8**
zerocracy/farm#209 - added project title.
 * Title is unique
 * Title is mandatory element
 * Title resticted by pattern `[\d\w._-]{3,}`
 * Set to project id by default (upgrade)

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this pull request

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#105` is in scope.

**Comment by 0crat** [comment]
+15 points just awarded to @g4s8, total is [+1455](http://www.0crat.com/u/g4s8).

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor release, tag is `0.39`

**Comment by yegor256** [comment]
@g4s8 there was a bug, just fixed it in 89cd183 I wonder, how can we prevent that from happening...

**Comment by yegor256** [comment]
@rultor release, tag is `0.40.1`

**Comment by yegor256** [comment]
@rultor release, tag is `0.40.1`

**Comment by g4s8** [comment]
@yegor256 I think we can write some kind of tests for upgrades. It may be target xml file which will be upgraded and and simple script with xpath assertions. We can place them in directories named as upgrade version.

**Comment by yegor256** [comment]
@g4s8 yes, sounds like a plan, feel free to submit a ticket

**Pull request merged**
