### PR TITLE
Couple of typos in terms.md

### PR DESCRIPTION
**Pull request by llorllale**
Just a couple of typos.

Also, not sure about this but isn't the year in the following paragraph wrong?

> The following red paragraphs are here only for the period of beta testing, which we started on January 5, 2017. We are planning to launch the first stable version in March 2017.

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#238](https://github.com/zerocracy/datum/issues/238) is now in scope, role is `REV`

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#238` is not assigned, can't get start time

**Comment by yegor256** [comment]
@llorllale thanks, you are right about the year, fixed in 874c3ab

**Comment by 0crat** [comment]
The job [#238](https://github.com/zerocracy/datum/issues/238) is now out of scope

**Pull request merged**
