### PR TITLE
Project options

### PR DESCRIPTION
**Pull request by g4s8**
#403 - added project options

### CODE REVIEW

**Comment by g4s8** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job [#404](https://github.com/zerocracy/datum/issues/404) is now in scope, role is `REV`

**Comment by g4s8** [comment]
@rultor merge

**Comment by g4s8** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#404` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#404](https://github.com/zerocracy/datum/issues/404) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Pull request merged**
