### PR TITLE
Reordered architects

### PR DESCRIPTION
**Pull request by krzyk**
Slight cleanup of .rultor.yml file, davvd is no longer operational, g4s8 should be at the top of architects so he will get the requests for merging.
Commanders are not needed, it will take the architect for that.

### CODE REVIEW

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) this pull request is too small, just 7 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @g4s8[/z](https://www.0crat.com/u/g4s8) please review this and merge or reject

**Comment by g4s8** [comment]
@krzyk thanks

**Comment by g4s8** [comment]
@rultor merge

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#352` is not assigned, can't get performer

**Pull request merged**
