### PR TITLE
advisers upgrade xsl 2.0

### PR DESCRIPTION
**Pull request by g4s8**
Changed advisers upgrade xsl version

### CODE REVIEW

**Comment by g4s8** [comment]
@yegor256 could you please merge and release this PR? This file break `XocumentTest` in farm.

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor release, tag is `0.60.1`

**Comment by yegor256** [comment]
@g4s8 done

**Comment by g4s8** [comment]
@yegor256 thanks

**Pull request merged**
