### PR TITLE
zerocracy/farm#64 Moved pm/hr to pm/staff

### PR DESCRIPTION
**Pull request by carlosmiranda**
zerocracy/farm#64 Merged pm/hr and pm/staff. Moved everything from pm/hr to pm/staff and removed pm/hr.

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this pull request

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@carlosmiranda you will have to move `upgrades` too.

**Comment by yegor256** [comment]
@carlosmiranda try `rake` before sending a pull request. You will need Ruby 2.2+ installed.

**Comment by carlosmiranda** [comment]
@yegor256 done, thanks for the tip. :)

**Comment by yegor256** [comment]
@rultor try to merge

**Comment by yegor256** [comment]
@rultor release, tag is `0.26`

**Comment by yegor256** [comment]
@rultor release, tag is `0.27`

**Pull request merged**
