### PR TITLE
zerocracy/farm#132 - fixed closing tag

### PR DESCRIPTION
**Pull request by g4s8**
zerocracy/farm#132 - fixed closing tag

### CODE REVIEW

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@g4s8 how did it work before and passed all tests??

**Comment by g4s8** [comment]
@yegor256 don't know why, but Nokogiri allows to use invalid xsl for transformation. I asked here https://stackoverflow.com/questions/45445392/nokogiri-xslt-can-transform-with-invalid-stylesheet

**Comment by yegor256** [comment]
@g4s8 upvoted. Let's see...

**Comment by yegor256** [comment]
@rultor release, tag is `0.32.1`

**Pull request merged**
