### PR TITLE
Reputation to invite

### PR DESCRIPTION
**Pull request by g4s8**
zerocracy/farm#389 - udated policy

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](http://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#226](https://github.com/zerocracy/datum/issues/226) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#226](https://github.com/zerocracy/datum/issues/226) is assigned to @yegor256[/z](http://www.0crat.com/u/yegor256). The budget is 15 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§27](http://datum.zerocracy.com/pages/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](http://www.0crat.com/u/yegor256) (the architect) right in this ticket. If you decide that this PR should not be accepted ever, also inform the architect.

**Comment by yegor256** [comment]
@g4s8 thanks!

**Comment by 0crat** [comment]
Order was successfully finished: +15 points just awarded to @yegor256[/z](http://www.0crat.com/u/yegor256), total is [+7510](http://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://datum.zerocracy.com/pages/policy.html#28): +15 points just awarded to @yegor256[/z](http://www.0crat.com/u/yegor256), total is [+7525](http://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@rultor release `0.51.6`

**Comment by 0crat** [comment]
The job [#226](https://github.com/zerocracy/datum/issues/226) is now out of scope

**Comment by 0crat** [comment]
Job [#226](https://github.com/zerocracy/datum/issues/226) was not in scope

**Comment by yegor256** [comment]
@rultor release tag is `0.51.6`

**Pull request merged**
