### PR TITLE
Missed table header

### PR DESCRIPTION
**Pull request by g4s8**
#179 - agenda & estimates todo

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](http://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#231](https://github.com/zerocracy/datum/issues/231) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#231](https://github.com/zerocracy/datum/issues/231) is assigned to @yegor256[/z](http://www.0crat.com/u/yegor256). The budget is 15 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§27](http://datum.zerocracy.com/pages/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](http://www.0crat.com/u/yegor256) (the architect) right in this ticket. If you decide that this PR should not be accepted ever, also inform the architect.

**Comment by yegor256** [comment]
@g4s8 I don't think this puzzle belongs to this repo... It should be in the `farm`

**Comment by g4s8** [comment]
@yegor256 you are right. But I can't create it in `farm` because of this issue: https://github.com/yegor256/pdd/issues/89

**Comment by yegor256** [comment]
@g4s8 just a create a bug, not a puzzle

**Comment by g4s8** [comment]
@yegor256 I moved it to zerocracy/farm#423. Now this PR about missed table header in `xsl` only

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
Order was successfully finished: +15 points just awarded to @yegor256[/z](http://www.0crat.com/u/yegor256), total is [+7605](http://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://datum.zerocracy.com/pages/policy.html#28): +15 points just awarded to @yegor256[/z](http://www.0crat.com/u/yegor256), total is [+7620](http://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
This pull request [#231](https://github.com/zerocracy/datum/issues/231) is assigned to @yegor256[/z](http://www.0crat.com/u/yegor256). The budget is 15 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§27](http://datum.zerocracy.com/pages/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](http://www.0crat.com/u/yegor256) (the architect) right in this ticket. If you decide that this PR should not be accepted ever, also inform the architect.

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#231` already assigned to @yegor256, can't assign to @yegor256

**Comment by 0crat** [comment]
@yegor256[/z](http://www.0crat.com/u/yegor256) resigned from [#231](https://github.com/zerocracy/datum/issues/231), since the job is not in scope anymore

**Comment by 0crat** [comment]
The job [#231](https://github.com/zerocracy/datum/issues/231) is now out of scope

**Pull request merged**
