### PR TITLE
Create slack link from project id

### PR DESCRIPTION
**Pull request by g4s8**
zerocracy/farm#208 - create slack link from project id:
```xml
<catalog>
  <project id="111" />
</catalog>
```
will be
```xml
<catalog>
  <project id="111">
    <links>
      <link rel="slack" href="111" />
    </links>
  </project>
</catalog>

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](http://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#224](https://github.com/zerocracy/datum/issues/224) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#224](https://github.com/zerocracy/datum/issues/224) is assigned to @yegor256[/z](http://www.0crat.com/u/yegor256). The budget is 15 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§27](http://datum.zerocracy.com/pages/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](http://www.0crat.com/u/yegor256) (the architect) right in this ticket. If you decide that this PR should not be accepted ever, also inform the architect.

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
Order was successfully finished: +15 points just awarded to @yegor256[/z](http://www.0crat.com/u/yegor256), total is [+7405](http://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://datum.zerocracy.com/pages/policy.html#28): +15 points just awarded to @yegor256[/z](http://www.0crat.com/u/yegor256), total is [+7420](http://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
This pull request [#224](https://github.com/zerocracy/datum/issues/224) is assigned to @yegor256[/z](http://www.0crat.com/u/yegor256). The budget is 15 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§27](http://datum.zerocracy.com/pages/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](http://www.0crat.com/u/yegor256) (the architect) right in this ticket. If you decide that this PR should not be accepted ever, also inform the architect.

**Comment by 0crat** [comment]
@yegor256[/z](http://www.0crat.com/u/yegor256) resigned from [#224](https://github.com/zerocracy/datum/issues/224), since the job is not in scope anymore

**Comment by 0crat** [comment]
The job [#224](https://github.com/zerocracy/datum/issues/224) is now out of scope

**Comment by 0crat** [comment]
Job [#224](https://github.com/zerocracy/datum/issues/224) was not in scope

**Comment by g4s8** [comment]
@yegor256 could you please release this changes?

**Comment by yegor256** [comment]
@rultor release, tag is `0.51.6`

**Comment by yegor256** [comment]
@rultor release, tag is `0.51.6`

**Comment by yegor256** [comment]
@rultor release, tag is `0.51.6`

**Comment by yegor256** [comment]
@rultor release, tag is `0.51.6`

**Comment by yegor256** [comment]
@g4s8 done

**Comment by g4s8** [comment]
@yegor256 thanks!

ср, 17 янв. 2018 г., 17:32 Yegor Bugayenko <notifications@github.com>:

**Pull request merged**
