### PR TITLE
zerocracy/farm#148 impediments.xml

### PR DESCRIPTION
**Pull request by carlosmiranda**
https://github.com/zerocracy/farm/issues/148: Added `impediments.xml`

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this pull request

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#98` is in scope.

**Comment by 0crat** [comment]
+15 points just awarded to @carlosmiranda, total is [+765](http://www.0crat.com/u/carlosmiranda).

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor release tag is `0.37`

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#98` assigned to @caarlos0, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
Oops! You need to have one of these roles in order to do what you're trying to do: ARC, PO. I'm sorry to say this, but at the moment you've got no roles in this project (your GitHub login is "0crat").

**Comment by 0crat** [comment]
@caarlos0 this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [par.8](http://datum.zerocracy.com/pages/policy.html#8).

**Comment by 0crat** [comment]
Payment to ARC for closed pull request.: +15 points just awarded to @yegor256, total is [+5810](http://www.0crat.com/u/yegor256).

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @caarlos0, total is [+525](http://www.0crat.com/u/caarlos0).

**Pull request merged**
