### PR TITLE
zerocracy/farm#149 - version and timestamp

### PR DESCRIPTION
**Pull request by g4s8**
zerocracy/farm#149 - vesion and timestamp

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this pull request

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#62` is in scope.

**Comment by 0crat** [comment]
+15 points just awarded to @g4s8, total is [+435](http://www.0crat.com/u/g4s8).

**Comment by yegor256** [comment]
@g4s8 maybe it would be nice to introduce a test somewhere in `Rakefile`, which would guarantee that all `simple.xml` files have `@version` and `@updated`? Without such a test somebody else will make exactly the same mistake you made.

**Comment by g4s8** [comment]
@yegor256 added check in Rakefile

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@g4s8 thanks! In general, it's a good rule to always start with reproducing the problem. That will help us protect our code base against future issues of similar type.

**Comment by g4s8** [comment]
@yegor256 I fixed RuboCop issues, restart Rultor please

**Comment by yegor256** [comment]
@rultor merge

**Comment by g4s8** [comment]
> Fetching fork
> Connection reset by 192.30.253.113 port 22
> fatal: Could not read from remote repository.

@yegor256 looks like Rultor failed due to network problem on his side. Could you restart him please?

**Comment by yegor256** [comment]
@g4s8 there are issues with GitHub now: https://twitter.com/githubstatus/status/893484188762087424

**Comment by yegor256** [comment]
@rultor merge

**Comment by g4s8** [comment]
@yegor256 make a release please, I nee this code for zerocracy/farm#149

**Comment by yegor256** [comment]
@rultor release, tag is `0.32.3`

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#62` assigned to @carlosmiranda, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
@carlosmiranda resigned from `gh:zerocracy/datum#62`, please stop working.

**Pull request merged**
