### PR TITLE
fix typo in policy

### PR DESCRIPTION
**Pull request by amihaiemil**
@yegor256 There was a little typo on the policy.html page.

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this pull request

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#64` is in scope.

**Comment by 0crat** [comment]
+15 points just awarded to @amihaiemil, total is [+15](http://www.0crat.com/u/amihaiemil).

**Comment by yegor256** [comment]
@amihaiemil thanks!

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#64` assigned to @carlosmiranda, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
@carlosmiranda resigned from `gh:zerocracy/datum#64`, please stop working.

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#64` assigned to @g4s8, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
Oops! You need to have one of these roles in order to do what you're trying to do: ARC, PO. I'm sorry to say this, but at the moment you've got no roles in this project (your GitHub login is "0crat").

**Comment by 0crat** [comment]
Payment to ARC for closed pull request.: +15 points just awarded to @yegor256, total is [+5810](http://www.0crat.com/u/yegor256).

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @g4s8, total is [+2880](http://www.0crat.com/u/g4s8).

**Pull request merged**
