### PR TITLE
zerocracy/farm#83 - bans schema

### PR DESCRIPTION
**Pull request by g4s8**
zerocracy/farm#83 - added xsd for bans xml

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this pull request

**Comment by yegor256** [comment]
@g4s8 how do you know it works? You should create `simple.xml` (or any other name) file in `xml` directory. `rake` will pick it up automatically. Also, you can create a few files which names start with `-`: they must violate the XSD schema requirements. I guess I need to explain this mechanism in README :) Feel free to submit a ticket about it.

**Comment by g4s8** [comment]
@yegor256 I've added validation files and submited issue: #51

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor release, tag is `0.28`

**Comment by yegor256** [comment]
@g4s8 version 0.28 is ready, you can use it now

**Pull request merged**
