### PR TITLE
Applications

### PR DESCRIPTION
**Pull request by g4s8**
zerocracy/farm#1349 - save user applications in `applications.xml`

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#406](https://github.com/zerocracy/datum/issues/406) is now in scope, role is `REV`

**Comment by g4s8** [comment]
@rultor merge

**Comment by g4s8** [comment]
@rultor release, tag=`0.66`

**Comment by g4s8** [comment]
merged

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#406` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#406](https://github.com/zerocracy/datum/issues/406) is now out of scope

**Comment by 0crat** [comment]
Pull request [#406](https://github.com/zerocracy/datum/issues/406) was not merged, no payment for `ARC`, see [§28](http://www.zerocracy.com/policy.html#28)

**Pull request closed without merging**
