### PR TITLE
Added role to agenda and estimates

### PR DESCRIPTION
**Pull request by g4s8**
#179 - added role to agenda and estimates

### CODE REVIEW

**Comment by g4s8** [comment]
@yegor256 can you please take a look at Travis build log? I added upgrade xsl file for agenda and estimates named as `<version>-role.xsl`, but got this error:
> upgrades/pm/cost/estimates/0.51.3-role.xsl is not in the repo and doesn't start with 999

**Comment by 0crat** [comment]
[@yegor256](http://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#214](https://github.com/zerocracy/datum/issues/214) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#214](https://github.com/zerocracy/datum/issues/214) is assigned to [@yegor256](http://www.0crat.com/u/yegor256). The budget is 15 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§27](http://datum.zerocracy.com/pages/policy.html#27) and [§10](http://datum.zerocracy.com/pages/policy.html#10) and when you decide to accept the changes, inform [@yegor256](http://www.0crat.com/u/yegor256) right in this ticket.

**Comment by yegor256** [comment]
@rultor merge

**Comment by g4s8** [comment]
@yegor256 I renamed upgrades to `999-role.xsl`, is it correct?

**Comment by yegor256** [comment]
@g4s8 nope, it's a bug in Rakefile. Please, revert it back to how it was before, I will fix the script now.

**Comment by g4s8** [comment]
@yegor256 done in 3e4140a

**Comment by yegor256** [comment]
@rultor merge

**Comment by g4s8** [comment]
@yegor256 I excluded `md/_template.html` from xml validation in `Rakefile`, can you try again please

**Comment by yegor256** [comment]
@g4s8 why? I will just fix it now: 1a21021

**Comment by g4s8** [comment]
@yegor256 I reverted it and merged with master

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#214` is not assigned, can't get start time

**Comment by 0crat** [comment]
Order was successfully finished: +15 points just awarded to @yegor256[/z](http://www.0crat.com/u/yegor256), total is [+7435](http://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://datum.zerocracy.com/pages/policy.html#28): +15 points just awarded to @yegor256[/z](http://www.0crat.com/u/yegor256), total is [+7450](http://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#214](https://github.com/zerocracy/datum/issues/214) is now out of scope

**Pull request merged**
