### PR TITLE
Fixed members

### PR DESCRIPTION
**Pull request by g4s8**
#384 - fixed members xsd, added test to verify

### CODE REVIEW

**Comment by g4s8** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job [#400](https://github.com/zerocracy/datum/issues/400) is now in scope, role is `REV`

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#400` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#400](https://github.com/zerocracy/datum/issues/400) is now out of scope

**Pull request merged**
