### PR TITLE
People applied element

### PR DESCRIPTION
**Pull request by g4s8**
zerocracy/farm#653 - added people applied element and upgrade

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#332](https://github.com/zerocracy/datum/issues/332) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#332](https://github.com/zerocracy/datum/issues/332) is assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/791714108); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](https://www.0crat.com/u/yegor256) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer

**Comment by g4s8** [comment]
@yegor256 ping

**Comment by yegor256** [comment]
@rultor merge

**Comment by ypshenychka** [comment]
@carlosmiranda According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>The code reviewer found at least three problems in the code.
Comments were mostly about design problems, not cosmetic issues.

No issues were found during code review. 
Please confirm that you'll try to find at least three problems while future reviews.

**Comment by carlosmiranda** [comment]
@ypshenychka confirmed

**Comment by ypshenychka** [comment]
@carlosmiranda Thanks!

**Comment by ypshenychka** [comment]
@0crat quality bad

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by g4s8** [comment]
@yegor256 please, release new version with these changes.

**Comment by yegor256** [comment]
@rultor release, tag is `0.60.3`

**Comment by yegor256** [comment]
@g4s8 pay attention, I made it optional, since not everybody has this element. If the user has never applied and doesn't have a mentor, the element must be absent.

**Comment by yegor256** [comment]
@rultor release, tag is `0.60.3`

**Pull request merged**
