### PR TITLE
Blanks

### PR DESCRIPTION
**Pull request by g4s8**
zerocracy/farm#536 - blanks schema, xsl and tests

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#321](https://github.com/zerocracy/datum/issues/321) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#321](https://github.com/zerocracy/datum/issues/321) is assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/661849126). The budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](https://www.0crat.com/u/yegor256) (the architect) right in this ticket. If you decide that this PR should not be accepted ever, also inform the architect.

**Comment by yegor256** [comment]
@rultor merge

**Comment by g4s8** [comment]
@yegor256 Rultor failed because `XSL version 1.0 is not 2.0 in xsl/pmo/blanks.xsl`, but as I can see version is 1.0 in all other `xsl` files, do I need to change it to:
```xml
<xsl:stylesheet version="2.0">
```
?

**Comment by yegor256** [comment]
@g4s8 yes, change it to 2.0 please

**Comment by g4s8** [comment]
@yegor256 fixed, I changed it to `2.0`, BTW `rake` didn't fail on my machine with `1.0`

**Comment by yegor256** [comment]
@rultor merge

**Comment by carlosmiranda** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zerocracy/datum/issues/321#issuecomment-372881236))

@carlosmiranda This is what I know about this job, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#321](https://github.com/zerocracy/datum/issues/321) is [in scope](http://www.zerocracy.com/policy.html#14) for 6days
  * The role is `REV`
  * The job is assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) for [6days](http://www.zerocracy.com/policy.html#8)
  * There is a monetary reward attached
  * @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) will get 25% of their hourly rate for this job
  * Some equity will be [vested](http://www.zerocracy.com/policy.html#37) on completion
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 15 minutes/points
  * These users are banned and won't be assigned:
    * @g4s8[/z](https://www.0crat.com/u/g4s8): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C3NDPUA8L?q=%7Bjob%3A%27gh%3Azerocracy%2Fdatum%23321%27%7D) (restricted area)

**Comment by carlosmiranda** [comment]
@yegor256 can we close this job, seems `0crat` missed it

**Comment by yegor256** [comment]
@0crat out

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/zerocracy/datum/issues/321#issuecomment-373190851))

@yegor256 The job [#321](https://github.com/zerocracy/datum/issues/321) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by ypshenychka** [comment]
@carlosmiranda According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>The code reviewer found at least three problems in the code.
Comments were mostly about design problems, not cosmetic issues.

No issues were found during code review. 
Please confirm that you'll try to find at least three problems while future reviews.

**Comment by carlosmiranda** [comment]
@ypshenychka confirmed

**Comment by ypshenychka** [comment]
@carlosmiranda Thank you!

**Comment by ypshenychka** [comment]
@0crat quality bad since the code reviewer didn’t find any issues in the pull request

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Comment by 0crat** [comment]
> @0crat quality bad since the code reviewer didn’t find any issues in the pull request ([here](https://github.com/zerocracy/datum/issues/321#issuecomment-373301252))

@ypshenychka Thanks, but quality review is not required in this job

**Comment by 0crat** [comment]
Quality review completed: +8 points just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Pull request merged**
